### ISSUE TITLE
Not building on Fedora 42

### ISSUE THREAD

**Issue by mattodinaturas** [c---/applesmc-next#9]
Trying to build AppleSMC on Fedora 42 results in an error. 

Here is the output of the terminal:

```
pierpaolo@fedora:~$ sudo dkms install "applesmc-next/$TAG"
[sudo] password di pierpaolo: 
Deprecated feature: CLEAN (/var/lib/dkms/applesmc-next/0.1.5/source/dkms.conf)
Sign command: /lib/modules/6.15.3-200.fc42.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j8 KERNELRELEASE=6.15.3-200.fc42.x86_64 KVER=6.15.3-200.fc42.x86_64

Error! Bad return status for module build on kernel: 6.15.3-200.fc42.x86_64 (x86_64)
Consult /var/lib/dkms/applesmc-next/0.1.5/build/make.log for more information.
pierpaolo@fedora:~$
```

And here is the content of the logfile:

  ```
GNU nano 8.3                                           /var/lib/dkms/applesmc-next/0.1.5/build/make.log                                                        
DKMS (dkms-3.2.1) make.log for applesmc-next/0.1.5 for kernel 6.15.3-200.fc42.x86_64 (x86_64)
mer 25 giu 2025, 16:00:45, CEST

Building module(s)
# command: make -j8 KERNELRELEASE=6.15.3-200.fc42.x86_64 KVER=6.15.3-200.fc42.x86_64
make -C /lib/modules/6.15.3-200.fc42.x86_64/build M=`pwd`
make[1]: ingresso nella directory «/usr/src/kernels/6.15.3-200.fc42.x86_64»
make[2]: ingresso nella directory «/var/lib/dkms/applesmc-next/0.1.5/build»
  CC [M]  applesmc/applesmc.o
  CC [M]  sbs/sbs.o
applesmc/applesmc.c:43:10: fatal error: acpi/sbs.h: File o directory non esistente
   43 | #include <acpi/sbs.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[5]: *** [/usr/src/kernels/6.15.3-200.fc42.x86_64/scripts/Makefile.build:203: applesmc/applesmc.o] Error 1
make[4]: *** [/usr/src/kernels/6.15.3-200.fc42.x86_64/scripts/Makefile.build:461: applesmc] Error 2
make[4]: *** Attesa per i processi non terminati....
sbs/sbs.c:522:6: warning: no previous prototype for ‘sbs_hook_unregister’ [-Wmissing-prototypes]
  522 | void sbs_hook_unregister(struct acpi_battery_hook *hook)
      |      ^~~~~~~~~~~~~~~~~~~
sbs/sbs.c:529:6: warning: no previous prototype for ‘sbs_hook_register’ [-Wmissing-prototypes]
  529 | void sbs_hook_register(struct acpi_battery_hook *hook)
      |      ^~~~~~~~~~~~~~~~~
make[3]: *** [/usr/src/kernels/6.15.3-200.fc42.x86_64/Makefile:2043: .] Error 2
make[2]: *** [/usr/src/kernels/6.15.3-200.fc42.x86_64/Makefile:260: __sub-make] Error 2
make[2]: uscita dalla directory «/var/lib/dkms/applesmc-next/0.1.5/build»
make[1]: *** [Makefile:260: __sub-make] Error 2
make[1]: uscita dalla directory «/usr/src/kernels/6.15.3-200.fc42.x86_64»
make: *** [Makefile:9: all] Error 2

# exit code: 2
```

SOLUTION:
The solution was given to me by this post on the Arch AUR page for AppleSMC, which can be visited via this link: 
[https://aur.archlinux.org/packages/applesmc-next-dkms](url)

I adapted the command listed there and i run on terminal 
`sudo cp /usr/src/applesmc-next-0.1.5/sbs/acpi/sbs.h /usr/lib/modules/6.15.3-200.fc42.x86_64/build/include/acpi/`
then i run a kernel reinstall and ultimately a reboot. 

Now battery health charging is back up and running just fine :)

Hope this post helps fellow people with old macbooks

**Comment by Lerm** [comment]
This (failure to build on 6.15) should be fixed now as #10  is merged.

**Comment by mattodinaturas** [comment]
> This (failure to build on 6.15) should be fixed now as [#10](https://github.com/c---/applesmc-next/pull/10) is merged.

Hi, I tried now and it works, thanks!! However, following the readme instructions still causes failure in building, as applesmc-next-0.1.5 still points to the old commit. 
@c--- should create a new release linked to the new commit in order to have a fully functional module. 

Many thanks to all of you for your help :)

**Comment by cokfenasikerim** [comment]
nope it doesnt mate ,  i am getting this on both aur and when i try manually the same error , ive applied the path didnt work 
Error! Could not find module source directory.
Directory: /usr/src/applesmc-next-0.1.5 does not exist.
[root@archlinux applesmc-next-0.1.5]# dkms install "applesmc-next/$TAG"

**Comment by cokfenasikerim** [comment]
it as working before but i did reinstall my arch not working , ve tried aur non aur they both giving the same error 
[root@archlinux src]# dkms install "applesmc-next/$TAG"
Deprecated feature: CLEAN (/usr/src/applesmc-next-0.1.5/dkms.conf)
Creating symlink /var/lib/dkms/applesmc-next/0.1.5/source -> /usr/src/applesmc-next-0.1.5

Sign command: /usr/lib/modules/6.15.7-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s).....(bad exit status: 2)
Failed command:
make -j4 KERNELRELEASE=6.15.7-arch1-1 KVER=6.15.7-arch1-1

Error! Bad return status for module build on kernel: 6.15.7-arch1-1 (x86_64)
Consult /var/lib/dkms/applesmc-next/0.1.5/build/make.log for more information.
[root@archlinux src]# 

but the advice from the other fellow has worked , 

 cp /usr/src/applesmc-next-0.1.5/sbs/acpi/sbs.h /usr/lib/modules/6.15.3-200.fc42.x86_64/build/include/acpi/

**Comment by cokfenasikerim** [comment]
thank you for writing such a module anyway

**Comment by mattodinaturas** [comment]
> it as working before but i did reinstall my arch not working , ve tried aur non aur they both giving the same error [root@archlinux src]# dkms install "applesmc-next/$TAG" Deprecated feature: CLEAN (/usr/src/applesmc-next-0.1.5/dkms.conf) Creating symlink /var/lib/dkms/applesmc-next/0.1.5/source -> /usr/src/applesmc-next-0.1.5
> 
> Sign command: /usr/lib/modules/6.15.7-arch1-1/build/scripts/sign-file Signing key: /var/lib/dkms/mok.key Public certificate (MOK): /var/lib/dkms/mok.pub
> 
> Building module(s).....(bad exit status: 2) Failed command: make -j4 KERNELRELEASE=6.15.7-arch1-1 KVER=6.15.7-arch1-1
> 
> Error! Bad return status for module build on kernel: 6.15.7-arch1-1 (x86_64) Consult /var/lib/dkms/applesmc-next/0.1.5/build/make.log for more information. [root@archlinux src]#
> 
> but the advice from the other fellow has worked ,
> 
> cp /usr/src/applesmc-next-0.1.5/sbs/acpi/sbs.h /usr/lib/modules/6.15.3-200.fc42.x86_64/build/include/acpi/

Hi, as I said in my last comment the 0.1.5 tag is linked the the old commit, therefore if you follow the instructions written in the readme, it doesn't build. You have to clone the main branch, not the latest (but still old) tag.

```
sudo rm -rf /usr/src/applesmc-next-*
sudo git clone --depth 1 -b main https://github.com/c---/applesmc-next.git /usr/src/applesmc-next-0.1.6

sudo dkms add -m applesmc-next -v 0.1.6
sudo dkms build -m applesmc-next -v 0.1.6
sudo dkms install -m applesmc-next -v 0.1.6
```

In this way, you create a "fake" 0.1.6 version by yourself on your pc and you build that. Ofc before doing so, you have to remove the old module with

`sudo dkms remove applesmc-next --all`

Hope this helps. By the way, this workaround is necessary until @c--- releases a new version 0.1.6 linked to the new commit
